/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.55
 * Generated at: 2023-11-16 01:05:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gz.member.model.vo.Member;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/views/common/main.jsp", Long.valueOf(1699990394000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1699588138000L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1700048196000L));
    _jspx_dependants.put("jar:file:/D:/GgulZip/GgulZip/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.gz.member.model.vo.Member");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Insert title here</title>\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");

//ContextRoot(ContextPath)를 꺼내놓기 (메소드를 이용하여)
String contextPath = request.getContextPath();
//로그인 정보 꺼내놓기 
//session객체에 loginUser 객체와 alertMsg 메세지를 담아놓음 
Member loginMember = (Member) session.getAttribute("loginMember");
String alertMsg = (String) session.getAttribute("alertMsg");
//로그인 전 menubar.jsp 로딩되면 loginUser == null
//로그인 후 menubar.jsp 로딩되면 로그인한 회원정보담긴 Member객체
//로그인 전 menubar.jsp 로딩되면 alertMsg == null
//로그인 후 menubar.jsp 로딩되면 alertMsg == 성공메세지 

//쿠키정보(쿠키 배열)
Cookie[] cookies = request.getCookies();

//쿠키배열에서 필요한 쿠키정보를 추출하기 
//반복으로 돌려서 해당 쿠키의 이름을 찾고 그 쿠키의 값을 담아두기 
String saveId = "";
if (cookies != null) {
	for (Cookie c : cookies) {

		if ((c.getName()).equals("memberId")) {
	saveId = c.getValue();
		}
	}
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<!-- Vendor CSS Files -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<!-- Vendor JS Files -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(":root{\r\n");
      out.write("	--maincolor :#f1cd1b; <!--노란색-->\r\n");
      out.write("}\r\n");
      out.write(".nav-area {\r\n");
      out.write("	background-color: #ffe14d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	width: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("	font-size: 20px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	display: block;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	line-height: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu a:hover {\r\n");
      out.write("	background-color: #ccb020;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'SEBANG_Gothic_Bold';\r\n");
      out.write("	src:\r\n");
      out.write("		url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2104@1.0/SEBANG_Gothic_Bold.woff')\r\n");
      out.write("		format('woff');\r\n");
      out.write("	font-weight: normal;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#login-form button {\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("	background-color: rgb(255, 219, 41);\r\n");
      out.write("	border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rectangle {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 0.5px;\r\n");
      out.write("	background-color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 드롭다운 스타일*/\r\n");
      out.write(".nav_main {\r\n");
      out.write("	font-weight: 900;\r\n");
      out.write("	font-size: 1.1rem;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	flex-direction: row;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	padding: 0 12px 0 12px;\r\n");
      out.write("	top: 0;\r\n");
      out.write("	left: 0;\r\n");
      out.write("	right: 0;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_item {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	flex: 0 0 auto;\r\n");
      out.write("	margin: 0 3rem;\r\n");
      out.write("	font-weight:900;\r\n");
      out.write("	padding-top:2rem;\r\n");
      out.write("	padding-bottom:2rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_item>a {\r\n");
      out.write("	color: #000000;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_item>a:after {\r\n");
      out.write("	content: '';\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	left: 50%;\r\n");
      out.write("	top: -2px;\r\n");
      out.write("	width: 0;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background-color: #000000;\r\n");
      out.write("	transition: width 0.2s ease-in-out;\r\n");
      out.write("	transform: translateX(-50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav_item:hover>a:after {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown_main {\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	display: block;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	z-index: 1;\r\n");
      out.write("	background-color: #fffafa;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	align-items: center;\r\n");
      out.write("	border-radius: 3px;\r\n");
      out.write("	top: 3.9rem;\r\n");
      out.write("	right: 0rem;\r\n");
      out.write("	width: 11rem;\r\n");
      out.write("	border: 1px solid rgb(99, 96, 96);\r\n");
      out.write("	box-shadow: 0 40px 40px rgb(0 0 0/ 6%);\r\n");
      out.write("	opacity: 0;\r\n");
      out.write("	visibility: hidden;\r\n");
      out.write("	transform: translateY(-10px);\r\n");
      out.write("	transition: transform 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown_main a {\r\n");
      out.write("	display: block;\r\n");
      out.write("	color: #000000;\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-size: 1rem;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown_main a div {\r\n");
      out.write("	padding: 0.5rem 0rem 0.5rem 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown_king:hover .dropdown_main {\r\n");
      out.write("	opacity: 1;\r\n");
      out.write("	visibility: visible;\r\n");
      out.write("	transform: translateY(0);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown_main a:hover {\r\n");
      out.write("	background-color: #c9cac9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("<!--메뉴바 탑 헤더-->\r\n");
      out.write(".menubarTopHeader {\r\n");
      out.write("\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header{\r\n");
      out.write("       display:flex;\r\n");
      out.write("       flex-direction: column;\r\n");
      out.write("       align-items: center;\r\n");
      out.write("       justify-content: center;\r\n");
      out.write("       width: 100%\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("header.active {\r\n");
      out.write("    margin-bottom: 80px\r\n");
      out.write("}\r\n");
      out.write("header #sub{\r\n");
      out.write("	position: relative;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: flex-end;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    margin-top: 10px;\r\n");
      out.write("    border-bottom: 1px solid var(--alpha-10);\r\n");
      out.write("}\r\n");
      out.write("header #sub .login-area{\r\n");
      out.write("    display: flex;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: end;\r\n");
      out.write("    width: 1050px;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("}\r\n");
      out.write("header #main {\r\n");
      out.write("       display: flex;\r\n");
      out.write("       align-items: center;\r\n");
      out.write("       justify-content: center;\r\n");
      out.write("       width: 1050px;\r\n");
      out.write("       padding: 0;\r\n");
      out.write("       margin: 15px 0\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("header #main>div {\r\n");
      out.write("    flex: 1\r\n");
      out.write("}\r\n");
      out.write("header #main .logo {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("\r\n");
      out.write("    font-size: 3em;\r\n");
      out.write("    font-weight: 700\r\n");
      out.write("}\r\n");
      out.write("header #main .logo div {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    margin: auto;\r\n");
      out.write("    font-family: GangwonEduPowerExtraBoldA,sans-serif\r\n");
      out.write("}\r\n");
      out.write("header #main .logo div:hover {\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("}\r\n");
      out.write("header #nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    background-color: rgb(241, 205, 27);\r\n");
      out.write("    width:1050px;\r\n");
      out.write("    height:50px;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("header nav{\r\n");
      out.write("	 display: flex;\r\n");
      out.write("      flex-wrap: wrap;\r\n");
      out.write("      align-items: center;\r\n");
      out.write("      justify-content: start;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".user-info a{\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!--jstl 방식으로 contextPath를 다시 선언해주어야 jstl방식으로 contextPath를 이용해야한다. -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<!-- 회원 탈퇴시 받을 메시지 확인 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("		var msg = '");
      out.print(alertMsg);
      out.write("'; //이건 가능 (문자열 처리해주기[값자체로 나옴])\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		if(msg != 'null'){ \r\n");
      out.write("			alert(msg);\r\n");
      out.write("			");
session.removeAttribute("alertMsg");
      out.write("\r\n");
      out.write("		}		\r\n");
      out.write("		\r\n");
      out.write("		$(function(){\r\n");
      out.write("			\r\n");
      out.write("			//쿠키 아이디값 가져오기\r\n");
      out.write("			\r\n");
      out.write("			var saveId = \"");
      out.print(saveId);
      out.write("\";\r\n");
      out.write("			\r\n");
      out.write("			if(saveId!=\"\"){\r\n");
      out.write("				$(\"input[name=memberId]\").val(saveId);\r\n");
      out.write("				$(\"input[name=saveId]\").attr(\"checked\",true);\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	<header>\r\n");
      out.write("		<section id=\"sub\">\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("			<div class=\"login-area\">\r\n");
      out.write("				");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      boolean _jspx_th_c_005fchoose_005f0_reused = false;
      try {
        _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fchoose_005f0.setParent(null);
        int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
        if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("					");
            //  c:when
            org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
            boolean _jspx_th_c_005fwhen_005f0_reused = false;
            try {
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /views/common/menubar.jsp(329,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty loginMember}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("						<button onclick='window.location.href = \"");
                  out.print(request.getContextPath());
                  out.write("/views/chat/Chat.jsp\";'\r\n");
                  out.write("							style=\"border: none; background: none; margin-right: 10px;\">익명 채팅방</button>\r\n");
                  out.write("						<button\r\n");
                  out.write("							onclick='window.location.href = \"");
                  out.print(request.getContextPath());
                  out.write("/views/member/Login.jsp\";'\r\n");
                  out.write("							style=\"border: none; background: none; margin-right: 10px;\">로그인</button>\r\n");
                  out.write("						<button\r\n");
                  out.write("							onclick='window.location.href = \"");
                  out.print(request.getContextPath());
                  out.write("/views/member/memberEnrollForm.jsp\";'\r\n");
                  out.write("							style=\"border: none; background: none; margin-right: 20px;\">회원가입</button>\r\n");
                  out.write("					");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
            }
            out.write("\r\n");
            out.write("					");
            //  c:otherwise
            org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
            boolean _jspx_th_c_005fotherwise_005f0_reused = false;
            try {
              _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
              if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\r\n");
                  out.write("						<!--로그인 후 화면-->\r\n");
                  out.write("						<div class=\"user-info\">\r\n");
                  out.write("							<b>");
                  out.print(loginMember.getNickname());
                  out.write("님 환영합니다. &nbsp</b>\r\n");
                  out.write("							<a href=\"");
                  out.print(contextPath);
                  out.write("/myPage.me\">마이페이지</a> \r\n");
                  out.write("							<a href=\"");
                  out.print(contextPath);
                  out.write("/logout.me\">로그아웃</a>\r\n");
                  out.write("							\r\n");
                  out.write("						</div>\r\n");
                  out.write("					");
                  int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
              _jspx_th_c_005fotherwise_005f0_reused = true;
            } finally {
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
            }
            out.write("\r\n");
            out.write("				");
            int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        _jspx_th_c_005fchoose_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
      }
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</section>\r\n");
      out.write("		<section id=\"main\">\r\n");
      out.write("			<div class=\"logo\">\r\n");
      out.write("				<br>\r\n");
      out.write("				<div id=\"home\">\r\n");
      out.write("					<h2\r\n");
      out.write("						style=\"font-size: 48px; font-weight: bold; color: rgb(241, 205, 27); font-family: SEBANG_Gothic_Bold; display: inline;\">\r\n");
      out.write("						꿀.zip</h2>\r\n");
      out.write("					<img src=\"views/img/bee.png\" alt=\"Bee Image\" width=\"50\" height=\"50\"\r\n");
      out.write("						style=\"display: inline; margin-top: -15px\">\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("		<section id=\"nav\">\r\n");
      out.write("			<nav>\r\n");
      out.write("				<!-- 1번 메뉴 링크 -->\r\n");
      out.write("				<div class=\"nav_item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/nlist.no?currentPage=1\">공지사항</a>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("				<div class=\"dropdown_king nav_item\">\r\n");
      out.write("					<a href=\"#\">게시판</a>\r\n");
      out.write("					<div class=\"dropdown_main\">\r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/list.bo?currentPage=1&category=꿀팁\">\r\n");
      out.write("							<div>꿀팁게시판</div>\r\n");
      out.write("						</a> \r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/list.bo?currentPage=1&category=자유\">\r\n");
      out.write("							<div>자유게시판</div>\r\n");
      out.write("						</a> \r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/list.bo?currentPage=1&category=추천\">\r\n");
      out.write("							<div>추천게시판</div>\r\n");
      out.write("						</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("				<div class=\"nav_item\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/complainList.bo?currentPage=1\">신고/건의</a>\r\n");
      out.write("				</div>\r\n");
      out.write("		\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("		</section>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	</header>\r\n");
      out.write("	<br clear=\"both\">\r\n");
      out.write("	<!--float 해제 -->\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!--로그인 전 후 화면 나누기 -->\r\n");
      out.write("	<!--로그인 전 -->\r\n");
      out.write("	");

	if (loginMember == null) {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("        	function enrollPage(){\r\n");
      out.write("        		//아래와 같이 작성하면 디렉토리 구조가 노출이 되니 보안에 취약할 수 있다. \r\n");
      out.write("        		//location.href=\"/jsp/views/member/memberEnrollForm.jsp\";\r\n");
      out.write("        		//때문에 간단한 페이지 이동요청도 servlet을 거쳐서 요청에대한 응답페이지를 돌려받자.\r\n");
      out.write("        		console.log(\"회원가입 클릭\");\r\n");
      out.write("        		location.href=\"");
      out.print(contextPath);
      out.write("/enrollForm.me\";\r\n");
      out.write("        		\r\n");
      out.write("        	}\r\n");
      out.write("        	\r\n");
      out.write("        	function findidPage() {\r\n");
      out.write("        		location.href=\"");
      out.print(contextPath);
      out.write("/findId.me\";\r\n");
      out.write("        	}\r\n");
      out.write("        \r\n");
      out.write("        	function findpwPage() {\r\n");
      out.write("        		location.href=\"");
      out.print(contextPath);
      out.write("/findPwd.me\";\r\n");
      out.write("			}\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("	");

	} else {
	
      out.write('\r');
      out.write('\n');
      out.write('	');

	}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("    document.getElementById(\"home\").addEventListener(\"click\", function() {\r\n");
      out.write("        // 클릭 이벤트 처리\r\n");
      out.write("        window.location.href = \"");
      out.print(contextPath);
      out.write("\"; \r\n");
      out.write("        // 원하는 페이지로 이동\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("     <div>\n");
      out.write("        <div id=\"chat-messages\">\n");
      out.write("            ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/chat/Chat.jsp", out, false);
      out.write("\n");
      out.write("        </div> \n");
      out.write("     </div>\n");
      out.write("\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("main {\r\n");
      out.write("	position: relative;\r\n");
      out.write("	display: flex;\r\n");
      out.write("	align-items: flex-start;\r\n");
      out.write("	justify-content: center;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article{\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    align-items: center;\r\n");
      out.write("\r\n");
      out.write("    width: 1050px;\r\n");
      out.write("    min-width: 1050px;\r\n");
      out.write("}\r\n");
      out.write("article .mediaContent,.postContent{\r\n");
      out.write("	width:100%;\r\n");
      out.write("	display:flex;\r\n");
      out.write("	margin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mediaContent>div{\r\n");
      out.write("	margin:5px;\r\n");
      out.write("	width:50%;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".postContent>div{\r\n");
      out.write("	margin:5px;\r\n");
      out.write("	width:50%;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write(".youtubeArea{\r\n");
      out.write("	\r\n");
      out.write("	height:300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".postArea{\r\n");
      out.write("	height:300px;\r\n");
      out.write("}\r\n");
      out.write(".introSite{\r\n");
      out.write("	background-color:black; \r\n");
      out.write("	width:100%;\r\n");
      out.write("	margin-bottom:30px;\r\n");
      out.write("}\r\n");
      out.write(".introSite div{\r\n");
      out.write("	color:white;\r\n");
      out.write("}\r\n");
      out.write("<!--인기게시글 관련 style-->\r\n");
      out.write(".list-area > tbody tr:hover {\r\n");
      out.write("       	background-color : rgb(255, 225, 77);\r\n");
      out.write("       	cursor : pointer;\r\n");
      out.write("      }\r\n");
      out.write(".list-area {\r\n");
      out.write("	width:100%;\r\n");
      out.write("    text-align: center; /* 테이블 셀 내용 가운데 정렬 */\r\n");
      out.write("    border-collapse: none; /* 테이블 셀 경계선 따로 그리기 */\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(" .list-area th, .list-area td {\r\n");
      out.write("     padding: 5.4px; /* 셀 내용과 경계선 사이 여백 추가 */\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write(".list-area, .list-area th, .list-area td {\r\n");
      out.write("    border: none; /* 테이블 셀 경계선 모두 제거 */\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write(".list-area td{\r\n");
      out.write("	text-overflow: ellipsis;\r\n");
      out.write("    white-space: nowrap;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    max-width: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-area tr {\r\n");
      out.write("	border-bottom : 1px solid lightgray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".list-area th {\r\n");
      out.write("       background-color : rgb(241, 205, 27);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_area {\r\n");
      out.write("text-align: center;\r\n");
      out.write("padding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".search_area select {\r\n");
      out.write("	width: 150px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border: 0px;\r\n");
      out.write("}\r\n");
      out.write(".pageBarDiv{\r\n");
      out.write("	align-items:center;\r\n");
      out.write("}\r\n");
      out.write(".list-area tbody tr:hover{\r\n");
      out.write("	cursor:pointer;\r\n");
      out.write("	background-color: #f1ec6f; /* 어두운 배경색으로 변경하고자 하는 색상으로 수정 */\r\n");
      out.write("    transition: background-color 0.3s ease; /* 부드러운 전환을 위한 설정 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<script>\r\n");
      out.write("		\r\n");
      out.write("	    function getPopularPost(currentPage) {\r\n");
      out.write("	    	$(\".pageBarDiv\").empty();\r\n");
      out.write("	    	$(\".list-area>tbody\").empty();\r\n");
      out.write("	        $.ajax({\r\n");
      out.write("	            url: \"getPageInfo.po\",\r\n");
      out.write("	            data: {\r\n");
      out.write("	                currentPage: currentPage\r\n");
      out.write("	            },\r\n");
      out.write("	            success: function(result) {\r\n");
      out.write("					\r\n");
      out.write("	            	var currentPage = $(\"<input id='currentPage' type='hidden'>\").val(result.currentPage);\r\n");
      out.write("\r\n");
      out.write("	           		$(\".pageBarDiv\").append(currentPage);\r\n");
      out.write("	            	if(result.currentPage == 1){\r\n");
      out.write("	            		var preButton = $(\"<button class='btn btn-sm' onclick='prevPageClick()' disabled></button>\").text(\"이전\");\r\n");
      out.write("	            		$(\".pageBarDiv\").append(preButton);\r\n");
      out.write("	            \r\n");
      out.write("	\r\n");
      out.write("	            	}else{\r\n");
      out.write("	            		var  preButton = $(\"<button class='btn btn-sm' onclick='prevPageClick()'></button>\").text(\"이전\");\r\n");
      out.write("	            		$(\".pageBarDiv\").append(preButton);\r\n");
      out.write("	            		\r\n");
      out.write("	            	}\r\n");
      out.write("	            	for(var i=result.startPage; i <= result.endPage;i++ ){\r\n");
      out.write("	            		var button;\r\n");
      out.write("	            	\r\n");
      out.write("	            		if(result.currentPage == i){\r\n");
      out.write("	            			 button = $(\"<button class='btn btn-sm pageNo active' onclick='pageNoClick(this)'></button>\").text(i);\r\n");
      out.write("	            		}else{\r\n");
      out.write("	            			button = $(\"<button class='btn btn-sm pageNo' onclick='pageNoClick(this)'></button>\").text(i);\r\n");
      out.write("	            		}\r\n");
      out.write("	            		\r\n");
      out.write("	            		$(\".pageBarDiv\").append(button);\r\n");
      out.write("	            		\r\n");
      out.write("	            	}\r\n");
      out.write("	            	if(result.currentPage == result.maxPage){\r\n");
      out.write("	            		var nextButton = $(\"<button class='btn btn-sm' onclick='nextPageClick()' disabled></button>\").text(\"다음\");\r\n");
      out.write("	            		$(\".pageBarDiv\").append(nextButton);\r\n");
      out.write("	            		\r\n");
      out.write("	            	}else{\r\n");
      out.write("	            		var nextButton = $(\"<button class='btn btn-sm' onclick='nextPageClick()'></button>\").text(\"다음\");\r\n");
      out.write("	            		$(\".pageBarDiv\").append(nextButton);\r\n");
      out.write("	            	}\r\n");
      out.write("	            	\r\n");
      out.write("	                $.ajax({\r\n");
      out.write("	                    url: \"popularPost.po\",\r\n");
      out.write("	                    data: {\r\n");
      out.write("	                        standard: $(\".form-select\").val(),\r\n");
      out.write("	                        listCount: result.listCount,\r\n");
      out.write("	                        currentPage: result.currentPage,\r\n");
      out.write("	                        pageLimit: result.pageLimit,\r\n");
      out.write("	                        boardLimit: result.boardLimit,\r\n");
      out.write("	                        maxPage: result.maxPage,\r\n");
      out.write("	                        startPage: result.startPage,\r\n");
      out.write("	                        endPage: result.endPage\r\n");
      out.write("	                    },\r\n");
      out.write("	                    success: function(result) {\r\n");
      out.write("	                    	\r\n");
      out.write("	                        for (var i = 0; i < result.length; i++) {\r\n");
      out.write("	                            var tr = $(\"<tr></tr>\");\r\n");
      out.write("	                            var postNo = $(\"<th></th>\").text(result[i].postNo);\r\n");
      out.write("	                            var category = $(\"<td></td>\").text(result[i].categoryName);\r\n");
      out.write("	                            var title = $(\"<td></td>\").text(result[i].title);\r\n");
      out.write("	                            var count = $(\"<td></td>\").text(result[i].count);\r\n");
      out.write("	                            var likeCount = $(\"<td></td>\").text(result[i].likeCount);\r\n");
      out.write("	                            var interestCount = $(\"<td></td>\").text(result[i].interestCount);\r\n");
      out.write("	                            var writer = $(\"<td></td>\").text(result[i].nickname);\r\n");
      out.write("	                            var date = $(\"<td></td>\").text(result[i].postDate);\r\n");
      out.write("	                            tr.append(postNo, category, title, count, likeCount, interestCount, writer, date);\r\n");
      out.write("	                            $(\".list-area>tbody\").append(tr);\r\n");
      out.write("	                         \r\n");
      out.write("	                        }\r\n");
      out.write("	                    },\r\n");
      out.write("	                    error: function() {\r\n");
      out.write("	                        console.error(\"popularPost.po Ajax 오류\");\r\n");
      out.write("	                    }\r\n");
      out.write("	                });\r\n");
      out.write("	            },\r\n");
      out.write("	            error: function() {\r\n");
      out.write("	                console.error(\"getPageInfo.po Ajax 오류\");\r\n");
      out.write("	            }\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("	    window.onload = getPopularPost(1);\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("	 \r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		<main style=\"height: auto;\" id=\"main-content\">\r\n");
      out.write("		<article>\r\n");
      out.write("			<div class=\"introSite\">\r\n");
      out.write("				<div style=\"height:300px;\">\r\n");
      out.write("					<img src=\"resources/assets/img/main-card-black.png\" alt=\"main-card\"\r\n");
      out.write("								class=\"main-card\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"mediaContent\">\r\n");
      out.write("				\r\n");
      out.write("				<div style=\" background-color:red;\">\r\n");
      out.write("					<div class=\"youtubeArea\">\r\n");
      out.write("	\r\n");
      out.write("						<iframe style=\"width: 100%; height:100%;\" src=\"https://www.youtube.com/embed/iOJM4GUnE04?si=30Jdgkuno2_JOAQ4\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div style=\"background-color:blue;\">\r\n");
      out.write("					<div class=\"youtubeArea\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						<iframe style=\"width: 100%; height:100%;\" src=\"https://www.youtube.com/embed/WjKGpKtQHzA?si=Bu7-8D7KBgeF_zaT\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\" allowfullscreen></iframe>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("				\r\n");
      out.write("			\r\n");
      out.write("			<div style=\"height: 50px; display: flex; justify-content: space-between;\">\r\n");
      out.write("				<h5 style=\"color: var(--maincolor); font-family: 'SEBANG_Gothic_Bold'; margin:0;\">인기 게시글</h5>\r\n");
      out.write("				<select class=\"form-select form-select-sm\" style=\"width:150px; height:35px;\">\r\n");
      out.write("				  <option value=\"1\" selected>조회순</option>\r\n");
      out.write("				  <option value=\"2\">좋아요순</option>\r\n");
      out.write("				  <option value=\"3\">관심등록순</option>\r\n");
      out.write("				</select>\r\n");
      out.write("				<script>\r\n");
      out.write("					//정렬 기준 select에 변화가 있으면\r\n");
      out.write("					$(\".form-select\").change(function(){\r\n");
      out.write("						 $(\".list-area>tbody\").empty();\r\n");
      out.write("						getPopularPost(1);\r\n");
      out.write("					});\r\n");
      out.write("					\r\n");
      out.write("				</script>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<table class=\"list-area\" align=\"center\" border = \"1\">\r\n");
      out.write("				\r\n");
      out.write("				<colgroup>\r\n");
      out.write("				      <col width=\"5%\" />\r\n");
      out.write("				      <col width=\"10%\" />\r\n");
      out.write("				      <col width=\"15%\" />\r\n");
      out.write("				      <col width=\"5%\" />\r\n");
      out.write("				      <col width=\"5%\" />\r\n");
      out.write("				      <col width=\"5%\" />\r\n");
      out.write("				      <col width=\"10%\" />\r\n");
      out.write("				      <col width=\"10%\" />\r\n");
      out.write("				</colgroup>\r\n");
      out.write("				<thead style=\" color: black; height:45px ;font-family: GmarketSansMedium; font-size : 13px\">\r\n");
      out.write("					<tr>\r\n");
      out.write("						<th>글번호</th>\r\n");
      out.write("						<th>카테고리</th>\r\n");
      out.write("						<th>제목</th>\r\n");
      out.write("						<th>조회수</th>\r\n");
      out.write("						<th>좋아요</th>\r\n");
      out.write("						<th>관심글</th>\r\n");
      out.write("						<th>작성자</th>\r\n");
      out.write("						<th>작성일</th>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("			<tbody>\r\n");
      out.write("				\r\n");
      out.write("			</tbody>\r\n");
      out.write("			</table>	\r\n");
      out.write("			\r\n");
      out.write("			<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("			<script>\r\n");
      out.write("			\r\n");
      out.write("			//행 클릭시 게시글 상세보기로 이동\r\n");
      out.write("			$(function(){\r\n");
      out.write("				$(\".list-area>tbody\").on(\"click\",\"tr\",function(){\r\n");
      out.write("				\r\n");
      out.write("					location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/detail.bo?postNo=\"+$(this).children().eq(0).text();\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("			});\r\n");
      out.write("			</script>\r\n");
      out.write("			\r\n");
      out.write("			<br>\r\n");
      out.write("			\r\n");
      out.write("			<!-- 페이징바 -->\r\n");
      out.write("			<div align=\"center\" class=\"pageBarDiv\" >\r\n");
      out.write("			    \r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("	\r\n");
      out.write("			<script>\r\n");
      out.write("				function prevPageClick(){\r\n");
      out.write("					\r\n");
      out.write("					getPopularPost(parseInt($(\"#currentPage\").val())-1);\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				function pageNoClick(button){\r\n");
      out.write("					\r\n");
      out.write("					$(button).addClass('active');\r\n");
      out.write("					getPopularPost($(button).text());\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("				function nextPageClick(){\r\n");
      out.write("\r\n");
      out.write("					getPopularPost(parseInt($(\"#currentPage\").val())+1);	\r\n");
      out.write("					\r\n");
      out.write("				}\r\n");
      out.write("			</script>\r\n");
      out.write("			<br><br><br>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</article>\r\n");
      out.write("		\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "views/common/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/common/menubar.jsp(287,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /views/common/menubar.jsp(287,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/common/menubar.jsp(287,1) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/common/menubar.jsp(289,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.deleteMemAlert}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<script>\r\n");
          out.write("    		alert(\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.deleteMemAlert}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\");\r\n");
          out.write("    		");
          if (_jspx_meth_c_005fremove_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("    	</script>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fremove_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:remove
    org.apache.taglibs.standard.tag.common.core.RemoveTag _jspx_th_c_005fremove_005f0 = (org.apache.taglibs.standard.tag.common.core.RemoveTag) _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.common.core.RemoveTag.class);
    boolean _jspx_th_c_005fremove_005f0_reused = false;
    try {
      _jspx_th_c_005fremove_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fremove_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /views/common/menubar.jsp(292,6) name = var type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setVar("deleteMemAlert");
      // /views/common/menubar.jsp(292,6) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fremove_005f0.setScope("session");
      int _jspx_eval_c_005fremove_005f0 = _jspx_th_c_005fremove_005f0.doStartTag();
      if (_jspx_th_c_005fremove_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fremove_0026_005fvar_005fscope_005fnobody.reuse(_jspx_th_c_005fremove_005f0);
      _jspx_th_c_005fremove_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fremove_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fremove_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /views/common/menubar.jsp(391,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.grade eq '관리자'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					<div class=\"dropdown_king nav_item\">\r\n");
          out.write("						<a href=\"#\">관리자</a>\r\n");
          out.write("						<div class=\"dropdown_main\">\r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/selectUser.ad?currentPage=1\">\r\n");
          out.write("								<div>관리자페이지</div>\r\n");
          out.write("							</a> \r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/category.ad\">\r\n");
          out.write("								<div>카테고리</div>\r\n");
          out.write("							</a> \r\n");
          out.write("							<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/disable.ad\">\r\n");
          out.write("								<div>정지회원</div>\r\n");
          out.write("							</a>\r\n");
          out.write("						</div>\r\n");
          out.write("					</div>				\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
